version: "1.0.0"
application: "servidores"
servers:
  - name: "Servidor 1"
    config:
      os: "Ubuntu"
      memory: "32GB"
      disk: "400GB"
    connect:
      type_connection: "SSH"
      user: ""
      password: ""
      ip_address: ""
    commands:
      - name: "Atualizar Servidor"
        exec:
          - "cd /home"
          - "touch testando_comando.txt"
      - name: "Criar cliente"
        exec:
          - "cd /home"
          - "touch testando_comando_dois.txt"
  - name: "Servidor 2"
    config:
      os: "Red Hat"
      memory: "100GB"
      disk: "16TB"
    connect:
      type_connection: "SSH_KEY"
      user: ""
      location: ""
      ip_address: ""
    commands:
      - name: "Fazer backup"
        exec:
          - "cd /var/www/html"
          - "mkdir teste"